= Video quick build project
:backend: asciidoctor
:github-flavored:  // enables GitHub-specific features like tables, task lists, and fenced code blocks
ifndef::env-github[:icons: font]
ifdef::env-github[]
// Naughty Waco Temps
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
endif::[]
:toc: // gets a ToC after the title
:toclevels: 2
// :sectnums: // gets ToC sections to be numbered
:sectnumlevels: 3 // max # of numbering levels

== Summary
Isolate specific environments for:

* *Develop*

All artifacts in a subdir under /tmp, with automatic setup and cleanup
Loging

* *Test*

ShellSpec managed

* *Deploy*

Would use real life hardware and environment 

== Workflow

The first thing is to determine which environment the script is being run under.
The variable ENV should be set from environments.sh in Development and Deploy; and in the *_spec.sh files for Testing.
ENV should pass on all scripts without being reset, so be declared as
readonly ENV=...   # or
const ENV=...      # when inside a function

Then Testing parameters should be declared in environments.sh to the same extent than for Development and Deploy.
And then other parameters necessary for testing in the *_spec.sh files.

== Technically

Bash scripts should be sourced from one another, keeping the environment consistent.

Each script should be individually ran & tested.


== Lessons learned: Technical issues or time over-consuming steps encountered during project & resolutions / mitigations

define ROOT_DIR in the main and submodules, it is not used in the environment file

`"ROOT="$(cd "${BASH_SOURCE[0]%/*.sh}" && pwd)" && +
. "$ROOT"/lib/environments.sh && +
cd "$ROOT" || exit 1
"`

